// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package keystone

import (
	"context"
	"database/sql"
)

const ListDomains = `-- name: ListDomains :many
SELECT 
    id,
    name,
    COALESCE(description, '') as description,
    enabled
FROM project 
WHERE is_domain = 1 AND id != '<<keystone.domain.root>>'
`

type ListDomainsRow struct {
	ID          string
	Name        string
	Description string
	Enabled     sql.NullBool
}

func (q *Queries) ListDomains(ctx context.Context) ([]ListDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDomainsRow
	for rows.Next() {
		var i ListDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListGroups = `-- name: ListGroups :many
SELECT 
    id,
    domain_id,
    name,
    COALESCE(description, '') as description
FROM ` + "`" + `group` + "`" + `
`

type ListGroupsRow struct {
	ID          string
	DomainID    string
	Name        string
	Description string
}

func (q *Queries) ListGroups(ctx context.Context) ([]ListGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListProjects = `-- name: ListProjects :many
SELECT 
    p.id,
    p.name,
    COALESCE(p.description, '') as description,
    p.enabled,
    p.domain_id,
    COALESCE(p.parent_id, '') as parent_id,
    p.is_domain,
    COALESCE(GROUP_CONCAT(pt.name SEPARATOR ','), '') as tags
FROM project p
LEFT JOIN project_tag pt ON p.id = pt.project_id
WHERE p.is_domain = 0
GROUP BY p.id, p.name, p.description, p.enabled, p.domain_id, p.parent_id, p.is_domain
`

type ListProjectsRow struct {
	ID          string
	Name        string
	Description string
	Enabled     sql.NullBool
	DomainID    string
	ParentID    string
	IsDomain    bool
	Tags        interface{}
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Enabled,
			&i.DomainID,
			&i.ParentID,
			&i.IsDomain,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRegions = `-- name: ListRegions :many
SELECT 
    id,
    COALESCE(description, '') as description,
    COALESCE(parent_region_id, '') as parent_region_id
FROM region
`

type ListRegionsRow struct {
	ID             string
	Description    string
	ParentRegionID string
}

func (q *Queries) ListRegions(ctx context.Context) ([]ListRegionsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegionsRow
	for rows.Next() {
		var i ListRegionsRow
		if err := rows.Scan(&i.ID, &i.Description, &i.ParentRegionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsers = `-- name: ListUsers :many
SELECT 
    id,
    enabled,
    domain_id,
    COALESCE(default_project_id, '') as default_project_id,
    created_at,
    last_active_at
FROM user
`

type ListUsersRow struct {
	ID               string
	Enabled          sql.NullBool
	DomainID         string
	DefaultProjectID string
	CreatedAt        sql.NullTime
	LastActiveAt     sql.NullTime
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, ListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Enabled,
			&i.DomainID,
			&i.DefaultProjectID,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
