// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package nova

import (
	"context"
	"database/sql"
)

const ComputeNodeGetAll = `-- name: ComputeNodeGetAll :many
SELECT 
    id,
    uuid,
    host,
    hypervisor_hostname,
    hypervisor_type,
    hypervisor_version,
    vcpus,
    vcpus_used,
    memory_mb,
    memory_mb_used,
    local_gb,
    local_gb_used,
    disk_available_least,
    free_ram_mb,
    free_disk_gb,
    current_workload,
    running_vms,
    cpu_allocation_ratio,
    ram_allocation_ratio,
    disk_allocation_ratio,
    deleted
FROM compute_nodes
WHERE deleted = 0
`

type ComputeNodeGetAllRow struct {
	ID                  int32
	Uuid                sql.NullString
	Host                sql.NullString
	HypervisorHostname  sql.NullString
	HypervisorType      string
	HypervisorVersion   int32
	Vcpus               int32
	VcpusUsed           int32
	MemoryMb            int32
	MemoryMbUsed        int32
	LocalGb             int32
	LocalGbUsed         int32
	DiskAvailableLeast  sql.NullInt32
	FreeRamMb           sql.NullInt32
	FreeDiskGb          sql.NullInt32
	CurrentWorkload     sql.NullInt32
	RunningVms          sql.NullInt32
	CpuAllocationRatio  sql.NullFloat64
	RamAllocationRatio  sql.NullFloat64
	DiskAllocationRatio sql.NullFloat64
	Deleted             sql.NullInt32
}

func (q *Queries) ComputeNodeGetAll(ctx context.Context) ([]ComputeNodeGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, ComputeNodeGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComputeNodeGetAllRow
	for rows.Next() {
		var i ComputeNodeGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Host,
			&i.HypervisorHostname,
			&i.HypervisorType,
			&i.HypervisorVersion,
			&i.Vcpus,
			&i.VcpusUsed,
			&i.MemoryMb,
			&i.MemoryMbUsed,
			&i.LocalGb,
			&i.LocalGbUsed,
			&i.DiskAvailableLeast,
			&i.FreeRamMb,
			&i.FreeDiskGb,
			&i.CurrentWorkload,
			&i.RunningVms,
			&i.CpuAllocationRatio,
			&i.RamAllocationRatio,
			&i.DiskAllocationRatio,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InstanceGetAll = `-- name: InstanceGetAll :many
SELECT 
    id,
    uuid,
    display_name,
    user_id,
    project_id,
    host,
    availability_zone,
    vm_state,
    power_state,
    task_state,
    memory_mb,
    vcpus,
    root_gb,
    ephemeral_gb,
    launched_at,
    terminated_at,
    instance_type_id,
    deleted
FROM instances
WHERE deleted = 0
`

type InstanceGetAllRow struct {
	ID               int32
	Uuid             string
	DisplayName      sql.NullString
	UserID           sql.NullString
	ProjectID        sql.NullString
	Host             sql.NullString
	AvailabilityZone sql.NullString
	VmState          sql.NullString
	PowerState       sql.NullInt32
	TaskState        sql.NullString
	MemoryMb         sql.NullInt32
	Vcpus            sql.NullInt32
	RootGb           sql.NullInt32
	EphemeralGb      sql.NullInt32
	LaunchedAt       sql.NullTime
	TerminatedAt     sql.NullTime
	InstanceTypeID   sql.NullInt32
	Deleted          sql.NullInt32
}

func (q *Queries) InstanceGetAll(ctx context.Context) ([]InstanceGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, InstanceGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstanceGetAllRow
	for rows.Next() {
		var i InstanceGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.DisplayName,
			&i.UserID,
			&i.ProjectID,
			&i.Host,
			&i.AvailabilityZone,
			&i.VmState,
			&i.PowerState,
			&i.TaskState,
			&i.MemoryMb,
			&i.Vcpus,
			&i.RootGb,
			&i.EphemeralGb,
			&i.LaunchedAt,
			&i.TerminatedAt,
			&i.InstanceTypeID,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ServiceGetAll = `-- name: ServiceGetAll :many
SELECT 
    id,
    uuid,
    host,
    ` + "`" + `binary` + "`" + `,
    topic,
    disabled,
    disabled_reason,
    last_seen_up,
    forced_down,
    version,
    report_count,
    deleted
FROM services
WHERE deleted = 0
  AND last_seen_up IS NOT NULL
  AND topic IS NOT NULL
`

type ServiceGetAllRow struct {
	ID             int32
	Uuid           sql.NullString
	Host           sql.NullString
	Binary         sql.NullString
	Topic          sql.NullString
	Disabled       sql.NullBool
	DisabledReason sql.NullString
	LastSeenUp     sql.NullTime
	ForcedDown     sql.NullBool
	Version        sql.NullInt32
	ReportCount    int32
	Deleted        sql.NullInt32
}

func (q *Queries) ServiceGetAll(ctx context.Context) ([]ServiceGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, ServiceGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceGetAllRow
	for rows.Next() {
		var i ServiceGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Host,
			&i.Binary,
			&i.Topic,
			&i.Disabled,
			&i.DisabledReason,
			&i.LastSeenUp,
			&i.ForcedDown,
			&i.Version,
			&i.ReportCount,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
