// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package heat

import (
	"context"
)

const StackGetAll = `-- name: StackGetAll :many
SELECT 
  s.id,
  COALESCE(s.name, '') as name,
  COALESCE(s.status, '') as status,
  COALESCE(s.action, '') as action,
  COALESCE(s.tenant, '') as tenant
FROM stack s
WHERE s.deleted_at IS NULL
`

type StackGetAllRow struct {
	ID     string
	Name   string
	Status string
	Action string
	Tenant string
}

func (q *Queries) StackGetAll(ctx context.Context) ([]StackGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, StackGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StackGetAllRow
	for rows.Next() {
		var i StackGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Action,
			&i.Tenant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
