// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package novaapi

import (
	"context"
	"database/sql"
)

const AggregateGetAll = `-- name: AggregateGetAll :many
SELECT 
    id,
    uuid,
    name,
    created_at,
    updated_at
FROM aggregates
`

type AggregateGetAllRow struct {
	ID        int32
	Uuid      sql.NullString
	Name      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) AggregateGetAll(ctx context.Context) ([]AggregateGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, AggregateGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateGetAllRow
	for rows.Next() {
		var i AggregateGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const AggregateHostGetAll = `-- name: AggregateHostGetAll :many
SELECT 
    ah.id,
    ah.host,
    ah.aggregate_id,
    a.name as aggregate_name,
    a.uuid as aggregate_uuid
FROM aggregate_hosts ah
JOIN aggregates a ON ah.aggregate_id = a.id
`

type AggregateHostGetAllRow struct {
	ID            int32
	Host          sql.NullString
	AggregateID   int32
	AggregateName sql.NullString
	AggregateUuid sql.NullString
}

func (q *Queries) AggregateHostGetAll(ctx context.Context) ([]AggregateHostGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, AggregateHostGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregateHostGetAllRow
	for rows.Next() {
		var i AggregateHostGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.AggregateID,
			&i.AggregateName,
			&i.AggregateUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FlavorGetAll = `-- name: FlavorGetAll :many
SELECT 
    id,
    flavorid,
    name,
    vcpus,
    memory_mb,
    root_gb,
    ephemeral_gb,
    swap,
    rxtx_factor,
    disabled,
    is_public
FROM flavors
`

type FlavorGetAllRow struct {
	ID          int32
	Flavorid    string
	Name        string
	Vcpus       int32
	MemoryMb    int32
	RootGb      sql.NullInt32
	EphemeralGb sql.NullInt32
	Swap        int32
	RxtxFactor  sql.NullFloat64
	Disabled    sql.NullBool
	IsPublic    sql.NullBool
}

func (q *Queries) FlavorGetAll(ctx context.Context) ([]FlavorGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, FlavorGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlavorGetAllRow
	for rows.Next() {
		var i FlavorGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Flavorid,
			&i.Name,
			&i.Vcpus,
			&i.MemoryMb,
			&i.RootGb,
			&i.EphemeralGb,
			&i.Swap,
			&i.RxtxFactor,
			&i.Disabled,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QuotaClassGetDefaults = `-- name: QuotaClassGetDefaults :many
SELECT 
    resource,
    hard_limit
FROM quota_classes
WHERE class_name = 'default'
`

type QuotaClassGetDefaultsRow struct {
	Resource  sql.NullString
	HardLimit sql.NullInt32
}

func (q *Queries) QuotaClassGetDefaults(ctx context.Context) ([]QuotaClassGetDefaultsRow, error) {
	rows, err := q.db.QueryContext(ctx, QuotaClassGetDefaults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaClassGetDefaultsRow
	for rows.Next() {
		var i QuotaClassGetDefaultsRow
		if err := rows.Scan(&i.Resource, &i.HardLimit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QuotaGetAll = `-- name: QuotaGetAll :many
SELECT 
    id,
    project_id,
    resource,
    hard_limit
FROM quotas
`

type QuotaGetAllRow struct {
	ID        int32
	ProjectID sql.NullString
	Resource  string
	HardLimit sql.NullInt32
}

func (q *Queries) QuotaGetAll(ctx context.Context) ([]QuotaGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, QuotaGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaGetAllRow
	for rows.Next() {
		var i QuotaGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Resource,
			&i.HardLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QuotaUsageGetAll = `-- name: QuotaUsageGetAll :many
SELECT 
    id,
    project_id,
    resource,
    in_use,
    reserved,
    until_refresh,
    user_id
FROM quota_usages
`

type QuotaUsageGetAllRow struct {
	ID           int32
	ProjectID    sql.NullString
	Resource     string
	InUse        int32
	Reserved     int32
	UntilRefresh sql.NullInt32
	UserID       sql.NullString
}

func (q *Queries) QuotaUsageGetAll(ctx context.Context) ([]QuotaUsageGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, QuotaUsageGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaUsageGetAllRow
	for rows.Next() {
		var i QuotaUsageGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Resource,
			&i.InUse,
			&i.Reserved,
			&i.UntilRefresh,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
