// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package octavia

import (
	"context"
	"database/sql"
)

const AmphoraGetAll = `-- name: AmphoraGetAll :many
SELECT
    id,
    compute_id,
    status,
    load_balancer_id,
    lb_network_ip,
    ha_ip,
    role,
    cert_expiration
FROM
    amphora
WHERE
    status != 'DELETED'
`

type AmphoraGetAllRow struct {
	ID             string
	ComputeID      sql.NullString
	Status         string
	LoadBalancerID sql.NullString
	LbNetworkIp    sql.NullString
	HaIp           sql.NullString
	Role           sql.NullString
	CertExpiration sql.NullTime
}

func (q *Queries) AmphoraGetAll(ctx context.Context) ([]AmphoraGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, AmphoraGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AmphoraGetAllRow
	for rows.Next() {
		var i AmphoraGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.ComputeID,
			&i.Status,
			&i.LoadBalancerID,
			&i.LbNetworkIp,
			&i.HaIp,
			&i.Role,
			&i.CertExpiration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LoadBalancerGetAllWithVIP = `-- name: LoadBalancerGetAllWithVIP :many
SELECT
    lb.id,
    lb.project_id,
    lb.name,
    lb.provisioning_status,
    lb.operating_status,
    lb.provider,
    v.ip_address as vip_address
FROM
    load_balancer lb
    LEFT JOIN vip v ON lb.id = v.load_balancer_id
WHERE
    lb.provisioning_status != 'DELETED'
`

type LoadBalancerGetAllWithVIPRow struct {
	ID                 string
	ProjectID          sql.NullString
	Name               sql.NullString
	ProvisioningStatus string
	OperatingStatus    string
	Provider           sql.NullString
	VipAddress         sql.NullString
}

func (q *Queries) LoadBalancerGetAllWithVIP(ctx context.Context) ([]LoadBalancerGetAllWithVIPRow, error) {
	rows, err := q.db.QueryContext(ctx, LoadBalancerGetAllWithVIP)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadBalancerGetAllWithVIPRow
	for rows.Next() {
		var i LoadBalancerGetAllWithVIPRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.ProvisioningStatus,
			&i.OperatingStatus,
			&i.Provider,
			&i.VipAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const PoolGetAll = `-- name: PoolGetAll :many
SELECT
    id,
    project_id,
    name,
    protocol,
    lb_algorithm,
    operating_status,
    load_balancer_id,
    provisioning_status
FROM
    pool
WHERE
    provisioning_status != 'DELETED'
`

type PoolGetAllRow struct {
	ID                 string
	ProjectID          sql.NullString
	Name               sql.NullString
	Protocol           string
	LbAlgorithm        string
	OperatingStatus    string
	LoadBalancerID     sql.NullString
	ProvisioningStatus string
}

func (q *Queries) PoolGetAll(ctx context.Context) ([]PoolGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, PoolGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoolGetAllRow
	for rows.Next() {
		var i PoolGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Protocol,
			&i.LbAlgorithm,
			&i.OperatingStatus,
			&i.LoadBalancerID,
			&i.ProvisioningStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
