// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package cinder

import (
	"context"
	"database/sql"
)

const QuotaGetAllWithUsage = `-- name: QuotaGetAllWithUsage :many
SELECT
    q.project_id,
    q.resource,
    q.hard_limit,
    COALESCE(qu.in_use, 0) as in_use
FROM
    quotas q
    LEFT JOIN quota_usages qu ON q.project_id = qu.project_id
        AND q.resource = qu.resource
        AND qu.deleted = 0
WHERE
    q.deleted = 0
`

type QuotaGetAllWithUsageRow struct {
	ProjectID sql.NullString
	Resource  string
	HardLimit sql.NullInt32
	InUse     int32
}

func (q *Queries) QuotaGetAllWithUsage(ctx context.Context) ([]QuotaGetAllWithUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, QuotaGetAllWithUsage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaGetAllWithUsageRow
	for rows.Next() {
		var i QuotaGetAllWithUsageRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Resource,
			&i.HardLimit,
			&i.InUse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QuotaGetProjectLimits = `-- name: QuotaGetProjectLimits :many
SELECT
    q.project_id,
    q.resource,
    q.hard_limit
FROM
    quotas q
WHERE
    q.deleted = 0
    AND (q.resource IN ('gigabytes', 'backup_gigabytes') OR q.resource LIKE 'gigabytes\_%')
`

type QuotaGetProjectLimitsRow struct {
	ProjectID sql.NullString
	Resource  string
	HardLimit sql.NullInt32
}

func (q *Queries) QuotaGetProjectLimits(ctx context.Context) ([]QuotaGetProjectLimitsRow, error) {
	rows, err := q.db.QueryContext(ctx, QuotaGetProjectLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaGetProjectLimitsRow
	for rows.Next() {
		var i QuotaGetProjectLimitsRow
		if err := rows.Scan(&i.ProjectID, &i.Resource, &i.HardLimit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const QuotaUsageGetAll = `-- name: QuotaUsageGetAll :many
SELECT
    qu.project_id,
    qu.resource,
    qu.in_use
FROM
    quota_usages qu
WHERE
    qu.deleted = 0
    AND qu.resource IN ('gigabytes', 'backup_gigabytes')
`

type QuotaUsageGetAllRow struct {
	ProjectID sql.NullString
	Resource  sql.NullString
	InUse     int32
}

func (q *Queries) QuotaUsageGetAll(ctx context.Context) ([]QuotaUsageGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, QuotaUsageGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaUsageGetAllRow
	for rows.Next() {
		var i QuotaUsageGetAllRow
		if err := rows.Scan(&i.ProjectID, &i.Resource, &i.InUse); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ServiceGetAll = `-- name: ServiceGetAll :many
SELECT
    uuid,
    host,
    ` + "`" + `binary` + "`" + ` as service,
    CASE
        WHEN disabled = 1 THEN 'disabled'
        ELSE 'enabled'
    END as admin_state,
    availability_zone as zone,
    disabled_reason,
    CASE
        WHEN TIMESTAMPDIFF (SECOND, updated_at, NOW()) <= 60 THEN 1
        ELSE 0
    END as state
FROM
    services
WHERE
    deleted = 0
`

type ServiceGetAllRow struct {
	Uuid           sql.NullString
	Host           sql.NullString
	Service        sql.NullString
	AdminState     string
	Zone           sql.NullString
	DisabledReason sql.NullString
	State          int32
}

func (q *Queries) ServiceGetAll(ctx context.Context) ([]ServiceGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, ServiceGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceGetAllRow
	for rows.Next() {
		var i ServiceGetAllRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Host,
			&i.Service,
			&i.AdminState,
			&i.Zone,
			&i.DisabledReason,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SnapshotCount = `-- name: SnapshotCount :one
SELECT
    COUNT(*) as count
FROM
    snapshots
WHERE
    deleted = 0
`

func (q *Queries) SnapshotCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, SnapshotCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const VolumeGetAll = `-- name: VolumeGetAll :many
SELECT id, project_id, size, volume_type_id, status, created_at, deleted_at
FROM volumes WHERE deleted = 0
`

type VolumeGetAllRow struct {
	ID           string
	ProjectID    sql.NullString
	Size         sql.NullInt32
	VolumeTypeID string
	Status       sql.NullString
	CreatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

func (q *Queries) VolumeGetAll(ctx context.Context) ([]VolumeGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, VolumeGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolumeGetAllRow
	for rows.Next() {
		var i VolumeGetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Size,
			&i.VolumeTypeID,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const VolumeGetAllWithAttachments = `-- name: VolumeGetAllWithAttachments :many
SELECT
    v.id,
    v.display_name as name,
    v.size,
    v.status,
    v.availability_zone,
    v.bootable,
    v.project_id,
    v.user_id,
    vt.name as volume_type,
    va.instance_uuid as server_id
FROM
    volumes v USE INDEX (volumes_service_uuid_idx)
    LEFT JOIN volume_types vt ON v.volume_type_id = vt.id
    LEFT JOIN volume_attachment va ON v.id = va.volume_id AND va.deleted = 0
WHERE
    (v.service_uuid IS NULL OR v.service_uuid IS NOT NULL)
    AND v.deleted = 0
`

type VolumeGetAllWithAttachmentsRow struct {
	ID               string
	Name             sql.NullString
	Size             sql.NullInt32
	Status           sql.NullString
	AvailabilityZone sql.NullString
	Bootable         sql.NullBool
	ProjectID        sql.NullString
	UserID           sql.NullString
	VolumeType       sql.NullString
	ServerID         sql.NullString
}

func (q *Queries) VolumeGetAllWithAttachments(ctx context.Context) ([]VolumeGetAllWithAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, VolumeGetAllWithAttachments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolumeGetAllWithAttachmentsRow
	for rows.Next() {
		var i VolumeGetAllWithAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.Status,
			&i.AvailabilityZone,
			&i.Bootable,
			&i.ProjectID,
			&i.UserID,
			&i.VolumeType,
			&i.ServerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const VolumeTypeGetAll = `-- name: VolumeTypeGetAll :many
SELECT
    id,
    name
FROM
    volume_types
WHERE
    deleted = 0
`

type VolumeTypeGetAllRow struct {
	ID   string
	Name sql.NullString
}

func (q *Queries) VolumeTypeGetAll(ctx context.Context) ([]VolumeTypeGetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, VolumeTypeGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VolumeTypeGetAllRow
	for rows.Next() {
		var i VolumeTypeGetAllRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
